services:
  markdown-transformer:
    build: .
    env_file: .env
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
